SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASSETS_PATH = './assets/'

BACKGROUND = ASSETS_PATH + 'background.jpeg'
BACKGROUND_WIDTH = 2957
BACKGROUND_HEIGHT = SCREEN_HEIGHT

SPRITES_PATH = ASSETS_PATH + 'sprites/'

BILL_GATES_FRONT = SPRITES_PATH + 'bill_front.png'
BILL_GATES_BACK = SPRITES_PATH + 'bill_back.png'
BILL_GATES_LEFT = SPRITES_PATH + 'bill_left.png'
BILL_GATES_RIGHT = SPRITES_PATH + 'bill_right.png'

MUSICS = ASSETS_PATH + 'musics/'

IN_GAME_SONG = MUSICS + 'in_game.mp3'

PLAYER_HEIGHT = 180
PLAYER_WIDTH = 60

PLAYABLE_SURFACE_WIDTH = BACKGROUND_WIDTH
PLAYABLE_SURFACE_HEIGHT = 160
