SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASSETS_PATH = './assets/'

BACKGROUND = ASSETS_PATH + 'background.jpeg'
BACKGROUND_WIDTH = 2957
BACKGROUND_HEIGHT = SCREEN_HEIGHT

MENU = ASSETS_PATH + 'menu.png'

SPRITES_PATH = ASSETS_PATH + 'sprites/'

BILL_GATES_FRONT = SPRITES_PATH + 'bill_front.png'
BILL_GATES_BACK = SPRITES_PATH + 'bill_back.png'
BILL_GATES_LEFT = SPRITES_PATH + 'bill_left.png'
BILL_GATES_RIGHT = SPRITES_PATH + 'bill_right.png'
BILL_GATES_FRONT_ATTACK = SPRITES_PATH + 'bill_front_attack.png'
BILL_GATES_BACK_ATTACK = SPRITES_PATH + 'bill_back_attack.png'
BILL_GATES_LEFT_ATTACK = SPRITES_PATH + 'bill_left_attack.png'
BILL_GATES_RIGHT_ATTACK = SPRITES_PATH + 'bill_right_attack.png'
BILL_GATES_SPEED = 5
BILL_GATES_NORMAL_ATTACK = 50
BILL_GATES_SPECIAL_ATTACK = 100
BILL_GATES_HEALTH = 100

STEVE_JOBS = SPRITES_PATH + 'steve_jobs.png'
STEVE_JOBS_ATTACKED = SPRITES_PATH + 'steve_jobs_attacked.png'
STEVE_JOBS_ATTACK = SPRITES_PATH + 'steve_jobs_attack.png'
STEVE_JOBS_ATTACK_ATTACKED = SPRITES_PATH + 'steve_jobs_attack_attacked.png'
STEVE_JOBS_HEALTH = 100
STEVE_JOBS_SPEED = 1
STEVE_JOBS_POWER = 5

MUSICS = ASSETS_PATH + 'musics/'

IN_GAME_SONG = MUSICS + 'in_game.mp3'
IN_MENU_SONG = MUSICS + 'in_menu.mp3'

SOUNDS = ASSETS_PATH + 'sounds/'

WILHELM = SOUNDS + 'wilhelm.mp3'
WILHELM_VOLUME = 0.1

PLAYER_HEIGHT = 180
PLAYER_WIDTH = 60

PLAYABLE_SURFACE_WIDTH = BACKGROUND_WIDTH
PLAYABLE_SURFACE_HEIGHT = 160

MAX_NB_ENNEMY = 20

HADOUKEN_SOUND = SOUNDS + 'hadouken.mp3'
HADOUKEN_IMAGE = SPRITES_PATH + 'hadouken.png'
HADOUKEN_VOLUME = 0.1
HADOUKEN_SPEED = 15
